team_dict = {
    'IND': 'Indiana Pacers',
    'OKC': 'Oklahoma City Thunder',
    'NYK': 'New York Knicks',
    'MIN': 'Minnesota Timberwolves',
    'DEN': 'Denver Nuggets',
    'BOS': 'Boston Celtics',
    'GSW': 'Golden State Warriors',
    'CLE': 'Cleveland Cavaliers',
    'HOU': 'Houston Rockets',
    'LAC': 'LA Clippers',
    'DET': 'Detroit Pistons',
    'LAL': 'Los Angeles Lakers',
    'MIL': 'Milwaukee Bucks',
    'ORL': 'Orlando Magic',
    'MIA': 'Miami Heat',
    'MEM': 'Memphis Grizzlies',
    'DAL': 'Dallas Mavericks',
    'ATL': 'Atlanta Hawks',
    'CHI': 'Chicago Bulls',
    'SAC': 'Sacramento Kings',
    'CHA': 'Charlotte Hornets',
    'NOP': 'New Orleans Pelicans',
    'PHX': 'Phoenix Suns',
    'BKN': 'Brooklyn Nets',
    'UTA': 'Utah Jazz',
    'TOR': 'Toronto Raptors',
    'PHI': 'Philadelphia 76ers',
    'SAS': 'San Antonio Spurs',
    'POR': 'Portland Trail Blazers',
    'WAS': 'Washington Wizards',

    # Special / exhibition / non-NBA teams in your dataset
    'SHQ': 'OGs',
    'CHK': 'Global Stars',
    'KEN': 'Young Stars',
    'CAN': 'Rising Stars',
    'TMC': 'Team C',
    'TMT': 'Team T',
    'TMM': 'Team M',
    'RCE': 'Team Rice',
    'TMG': 'Team G League',
    'BND': 'Team Bonds',
    'ULM': 'Ratiopharm Ulm',
    'NZB': 'New Zealand Breakers'
}