CREATE TABLE league_game_stats_raw (
    season_id        INTEGER NOT NULL,
    team_id          BIGINT NOT NULL,
    team_abbreviation VARCHAR(3) NOT NULL,
    team_name        TEXT NOT NULL,
    game_id          VARCHAR(10) NOT NULL,
    game_date        DATE NOT NULL,
    matchup          TEXT NOT NULL,
    wl               CHAR(1) NOT NULL,
    min              INTEGER NOT NULL,
    pts              INTEGER NOT NULL,
    fgm              INTEGER NOT NULL,
    fga              INTEGER NOT NULL,
    fg_pct           NUMERIC(5,3),
    fg3m             INTEGER NOT NULL,
    fg3a             INTEGER NOT NULL,
    fg3_pct          NUMERIC(5,3),
    ftm              INTEGER NOT NULL,
    fta              INTEGER NOT NULL,
    ft_pct           NUMERIC(5,3),  -- nullable (FTA = 0 case)
    oreb             INTEGER NOT NULL,
    dreb             INTEGER NOT NULL,
    reb              INTEGER NOT NULL,
    ast              INTEGER NOT NULL,
    stl              INTEGER NOT NULL,
    blk              INTEGER NOT NULL,
    tov              INTEGER NOT NULL,
    pf               INTEGER NOT NULL,
    plus_minus       NUMERIC(6,1)
);