CREATE TABLE team_game_stats_raw (
    season_id          INTEGER,
    team_id            BIGINT,
    team_abbreviation  VARCHAR(3),
    team_name          TEXT,
    game_id            VARCHAR(10),
    game_date          DATE,
    matchup            TEXT,
    wl                 CHAR(1),
    min                SMALLINT,
    pts                SMALLINT,
    fgm                SMALLINT,
    fga                SMALLINT,
    fg_pct             NUMERIC(5,3),
    fg3m               SMALLINT,
    fg3a               SMALLINT,
    fg3_pct            NUMERIC(5,3),
    ftm                SMALLINT,
    fta                SMALLINT,
    ft_pct             NUMERIC(5,3),
    oreb               SMALLINT,
    dreb               SMALLINT,
    reb                SMALLINT,
    ast                SMALLINT,
    stl                SMALLINT,
    blk                SMALLINT,
    tov                SMALLINT,
    pf                 SMALLINT,
    plus_minus         NUMERIC(5,1),
    PRIMARY KEY (game_id, team_id)
);